# Generated by Django 5.1.1 on 2024-09-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_registration_comments_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='participant_pictures/'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('participant', 'event')},
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.participant')),
            ],
            options={
                'unique_together': {('participant', 'event')},
            },
        ),
    ]
